project:
  type: website
  output-dir: docs

lang: es

website:
  title: "NOCTUA-Rec"
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - href: proyecto.qmd
        text: El proyecto
      - href: mapa.qmd
        text: Mapa resumen
      - href: participar.qmd
        text: ¿Cómo participar?

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    include-in-header: header.html

editor: visual

